<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Allow package downgrades for integration testing of all local packages -->
    <NoWarn>$(NoWarn);NU1605;NU1903</NoWarn>
    <!-- Set SolutionDir for packages that expect it -->
    <SolutionDir Condition="'$(SolutionDir)' == '' or '$(SolutionDir)' == '*Undefined*'">$(MSBuildProjectDirectory)\</SolutionDir>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KoreForge.AppLifecycle" Version="1.1.2" />
    <PackageReference Include="KoreForge.Kafka" Version="1.1.2" />
    <PackageReference Include="KoreForge.Logging" Version="1.1.2" />
    <PackageReference Include="KoreForge.Logging.Serilog" Version="1.1.2" />
    <PackageReference Include="KoreForge.Metrics" Version="1.1.2" />
    <PackageReference Include="KoreForge.Metrics.AspNet" Version="1.1.2" />
    <PackageReference Include="KoreForge.Time" Version="1.1.2" />
    <PackageReference Include="KoreForge.Web.Authorization" Version="1.1.2" />
    <PackageReference Include="KoreForge.Web.RestApi.Abstractions" Version="1.1.2" />
    <PackageReference Include="KoreForge.Web.RestApi.Observability" Version="1.1.2" />
    <PackageReference Include="KoreForge.Web.RestApi.Persistence" Version="1.1.2" />
  </ItemGroup>
</Project>